eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: svc-api
  autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  http:
    multipart:
      location: D:/zxMainPath/upload/tmp
zuul:
  routes:
    svc-user:
      path: /svc-user/**
      serviceId: svc-user
    svc-crm:
      path: /svc-crm/**
      serviceId: svc-crm
    svc-ews:
      path: /svc-ews/**
      serviceId: svc-crm
    svc-cm:
      path: /svc-cm/**
      serviceId: svc-cm
    svc-fri:
      path: /svc-fri/**
      serviceId: svc-fri
    svc-marke:
      path: /svc-marke/**
      serviceId: svc-marke
